# Generated by Django 3.0.7 on 2020-06-18 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200617_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
        migrations.AlterModelTable(
            name='choice',
            table=None,
        ),
        migrations.AlterModelTable(
            name='question',
            table=None,
        ),
    ]
